[package]
name = "hexagenmini"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "hexagenmini"
path = "src/main.rs"
test = false
bench = false

[dependencies]
rp2040-hal = { version = "0.11", features = ["rt"] }
embedded-hal = "1"

cortex-m = { version = "0.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7"

defmt = "1.0.1"
defmt-rtt = "1.0.0"
panic-probe = { version = "1.0", features = ["print-defmt"] }

rp2040-boot2 = "0.3"

usb-device = "0.3"
usbd-serial = "0.2.2"
itoa = "1"

[profile.release]
codegen-units = 1
debug = true
lto = true
