# SPDX-FileCopyrightText: 2025 hexaTune LLC
# SPDX-License-Identifier: MIT

name: 🧐 Commit Lint

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  commitlint:
    name: Commit Lint (hexaGenMini)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Lint commits
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: .github/.commitlintrc.yml
          failOnWarnings: true
